#include <iostream>
#include <fstream>
#include <string.h>
using namespace std;

#define code_file_name "code.cpp"

class CodeGenerator {

public:
	//Current max value of the state machine
	//Shared with all the instances of the CodeGenrator
	static int curr_state_number;

	//Generate the linear code given the user input
	void linear_code(string user_input);

	//Generate the state machine code given the user input
	void state_machine_code(string user_input);

	//Starts the code 
	void start();

	//Finishes the code
	void finish();

	//Inclues the functions for the gps
	void gps_code();

	//Inclues the functions for the bmp
	void bmp_code();

	//Inclues the functions for the communication
	void comm_code();

	//Inclues the functions for the system initial setup
	void initial_setup();
};


void CodeGenerator::linear_code(string user_input){

	CodeGenerator code_gen;

	//For each character in user_input, generate it's respective
	//piece of code
	for(int i=0; i<sizeof(user_input); i++){
		//For each number there is a respective code
		switch(user_input[i]){
			case '1':
				code_gen.gps_code();
				break;
			case '2':
				code_gen.bmp_code();
				break;
			case '3':
				code_gen.comm_code();
				break;
		}
	}

	return;
}

void CodeGenerator::state_machine_code(string user_input){

	CodeGenerator code_gen;

	//Opens the file
	ofstream code_file;
	string code;
	code_file.open(code_file_name, ios_base::app);

	//Initializes a state machine var
	code = "//State Machine state\n";
	code = "int state = 0;\n\n";

	//Opens the state machine
	code = "switch(state){\n";
	
	//Initial setup state
	//also increments the curr_state_number
	code = "case '" + to_string(CodeGenerator::curr_state_number++) + "':\n";

	//writes to the file
	code_file << code;
	//You need to close the file before call a function that opens it
	code_file.close();

	//Writes the initial setup
	code_gen.initial_setup();

	//Opens the file
	code_file.open(code_file_name, ios_base::app);

	//Another state
	code = "case '" + to_string(CodeGenerator::curr_state_number++) + "':\n";

	//writes to the file
	code_file << code;
	//You need to close the file before call a function that opens it
	code_file.close();

	//Write the linear code state
	code_gen.linear_code(user_input);

	//Opens the file
	code_file.open(code_file_name, ios_base::app);

	//Close the switch
	code = "}\n";

	//writes to the file
	code_file << code;
	//You need to close the file before call a function that opens it
	code_file.close();

	return;
}

void CodeGenerator::start(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	code_file.open(code_file_name);

	code = "//This code was generated by codeGenerator\n";
	//Fist, all the includes should be put here
	code = code + "#include<iostream>\n";
	//Namespace std, default in c++ applications
	code = code + "using namespace std;\n\n";
	//Starts the main function
	code = code + "int main(){\n";
	//Code....

	//Writes to file
	code_file << code;
	code_file.close();
}

void CodeGenerator::finish(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	//Open the file to append
	code_file.open(code_file_name, ios_base::app);

	//Writes the main return and closes the code
	code = "\n";
	code = code + "	return 0;\n";
	code = code + "}";

	//Writes to file
	code_file << code;
	code_file.close();
}

void CodeGenerator::gps_code(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	//Open the file to append
	code_file.open(code_file_name, ios_base::app);

	code = "\n";
	code = code + "	//Code for the gps\n";
	code = code + "	set_gps();\n";
	code = code + "	get_gps();\n";
	code = code + "\n";

	//Writes to file
	code_file << code;
	code_file.close();
}

void CodeGenerator::bmp_code(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	//Open the file to append
	code_file.open(code_file_name, ios_base::app);

	code = "\n";
	code = code + "	//Code for the bmp\n";
	code = code + "	set_bmp();\n";
	code = code + "	get_bmp();\n";
	code = code + "\n";

	//Writes to file
	code_file << code;
	code_file.close();
}

void CodeGenerator::comm_code(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	//Open the file to append
	code_file.open(code_file_name, ios_base::app);

	code = "\n";
	code = code + "	//Code for the communication\n";
	code = code + "	open_comm();\n";
	code = code + "	send_data();\n";
	code = code + "	close_comm();\n";
	code = code + "\n";

	//Writes to file
	code_file << code;
	code_file.close();
}

void CodeGenerator::initial_setup(){

	//Starts the generated code file
	ofstream code_file;
	string code;

	//Open the file to append
	code_file.open(code_file_name, ios_base::app);

	code = "\n";
	code = code + "	//Code for the initial setup\n";
	code = code + "	system_init();\n";
	code = code + "	system_config();\n";
	code = code + "\n";

	//Writes to file
	code_file << code;
	code_file.close();
}


//Initializes the state machine counter
int CodeGenerator::curr_state_number = 0;

int main(){

	string user_input;
	CodeGenerator code_gen;

	//Rads the user input
	cout << "Enter a string informing which componentes\n";
	cout << "you want to add to your system: \n\n";
	cout << "Options: \n1-GPS\n2-BMP\n3-Communication\n\nInput:";
	getline(cin, user_input);

	//Starts the code
	code_gen.start();
	//Write the linear code
	code_gen.state_machine_code(user_input);
	//Finishes the code
	code_gen.finish();

	return 0;
}