//This code was generated by codeGenerator
#include<iostream>

#include<2.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a;
    int b;
    float teste_1_return = teste_1(a, b);

    }

	return 0;
}