//This code was generated by codeGenerator
#include<iostream>

#include<mod1.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a
    float b
    f1(a, b);

	case '1':

    int a
    float b
    f1(a, b);

    bool 
    f2();

	case '2':

    bool 
    f2();

    int a
    float b
    f1(a, b);

    }

	return 0;
}