//This code was generated by codeGenerator
#include<iostream>

#include<teste_module.h>
#include<teste_module_2.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a
    float b
    teste_1(a, b);

    a a
    teste_2(a);

	case '1':

    a a
    teste_2(a);

    int a
    float b
    teste_1(a, b);

    }

	return 0;
}