//This code was generated by codeGenerator
#include<iostream>

#include<strato_link_v1.h>
#include<comm_v1.h>
#include<bmp.h>
#include<strato_link_v1.h>
#include<comm_v1.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

	case '1':

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

	case '2':

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    float a;
    int read_bmp_return = read_bmp(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    int a;
    int send_return = send(a);

    }

	return 0;
}