//This code was generated by codeGenerator
#include<iostream>

#include<strato_link_v2.h>
#include<comm_v1.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a;
    int strato_1_return = strato_1(a);

    float a;
    float strato_2_return = strato_2(a);

	case '1':

    int send_data_return = send_data();

    }

	return 0;
}