//This code was generated by codeGenerator
#include<iostream>

#include<strato_v3.h>
#include<comm.h>
#include<bmp.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    float a;
    int b;
    char c;
    int main_1_return = main_1(a, b, c);

    float a;
    int send_data_return = send_data(a);

	case '1':

    int a;
    float b;
    float c;
    float bmp_1_return = bmp_1(a, b, c);

    float a;
    int send_data_return = send_data(a);

    }

	return 0;
}