//This code was generated by codeGenerator
#include<iostream>

#include<strato.h>
#include<comm.h>
#include<bmp.h>

using namespace std;

int main(){
//State Machine state
int state = 0;

switch(state){

	case '0':

    int a;
    int b;
    int strato_1_return = strato_1(a, b);

    float strato_2_return = strato_2();

    float a;
    int send_data_return = send_data(a);

	case '1':

    int a;
    float b;
    float c;
    float bmp_1_return = bmp_1(a, b, c);

    float a;
    int send_data_return = send_data(a);

    }

	return 0;
}